version: "3"

services:
  channel:
    build:
      context: ../../
      dockerfile: ./docker/indexer-service/Dockerfile
    ports:
      - "42069:42069"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - NODE_ENV=production
      - PONDER_RPC_URL_84532=https://base-sepolia.g.alchemy.com/v2/o3VW3WRXrsXXMRX3l7jZxLUqhWyZzXBy
      - DATABASE_URL=postgresql://neondb_owner:npg_Jz6KCkb7gUyE@ep-hidden-bread-ae7jfj68-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
